options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # タグのついたコミットのブランチが 'main' か確認
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TAG_NAME=$(git tag --points-at HEAD 2>&1)
        if [ $? -ne 0 ]; then
          echo "This commit is not tagged. error $TAG_NAME"
          exit 1
        elif ! [[ "$TAG_NAME" =~ ^release ]]; then
          echo "This commit is tagged as $TAG_NAME, not as release. Build process ends with error."
          exit 1  # ^release にマッチしないタグはスキップ
        fi

  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlpipelineportfolio/poc-ph05-test', '.']

  # ビルドしたイメージを Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlpipelineportfolio/poc-ph05-test']

  # Cloud Run にデプロイ(changed region due to insane restriction)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'poc-ph05-test'
      - '--image'
      - 'gcr.io/mlpipelineportfolio/poc-ph05-test'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'