options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlpipelineportfolio/mdl06-handlerequest', '.']

  # ビルドしたイメージを Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlpipelineportfolio/mdl06-handlerequest']

  # Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mdl06-handlerequest'
      - '--image'
      - 'gcr.io/mlpipelineportfolio/mdl06-handlerequest'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'