options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlpipelineportfolio/poc-ph05-test', '.']

  # ビルドしたイメージを Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlpipelineportfolio/poc-ph05-test']

  # Cloud Run にデプロイ(changed region due to insane restriction)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'poc-ph05-test'
      - '--image'
      - 'gcr.io/mlpipelineportfolio/poc-ph05-test'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'