options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # タグのついたコミットのブランチが 'main' か確認
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git config --global init.defaultBranch main
        git remote -v
        git status
        git log --oneline -5
        git fetch --tags
        git tag
        REF_NAME=$(rev-parse --verify HEAD)
        echo "current commit $REF_NAME"
        REF_NAME=$(git log --pretty=format:%H -n 2 | tail -n 1)
        echo "parent commit $REF_NAME"
        TAG_NAME=$(git describe --tags $REF_NAME 2>/dev/null)
        if [ -z "$TAG_NAME" ]; then
          echo "No tag found for the parent commit."
          exit 1
        elif ! [[ "$TAG_NAME" =~ ^release ]]; then
          echo "This commit is tagged as $TAG_NAME, not as release. Build process ends with error."
          exit 1  # ^release にマッチしないタグはスキップ
        else
          echo "$TAG_NAME confirmed. Build Process procedes"
          exit 0
        fi

  # Docker イメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mlpipelineportfolio/poc-ph05-test', '.']

  # ビルドしたイメージを Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mlpipelineportfolio/poc-ph05-test']

  # Cloud Run にデプロイ(changed region due to insane restriction)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'poc-ph05-test'
      - '--image'
      - 'gcr.io/mlpipelineportfolio/poc-ph05-test'
      - '--platform'
      - 'managed'
      - '--region'
      - 'asia-east1'
      - '--allow-unauthenticated'