name: Upload folder 'uploadFromGitHub' to GCS bucket
on:
  push:
    branches:
      - 'main'

jobs:push
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'Set up Node.js 16'
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/564758604505/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'pj03-vertex-account@mlpipelineportfolio.iam.gserviceaccount.com'

    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: '/uploadFromGitHub'
        destination: 'gs://mlpipelineportfolio_bucket_01/'
