name: Upload folder 'uploadFromGitHub' to GCS bucket
on:
  push:
    branches:
      - 'main'

jobs:
  job_id:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v4'

    - id: 'getchangedfiles'
      run: |
          git fetch origin
          git diff --name-only HEAD^ HEAD > changed_files.txt
          cat changed_files.txt

    - id: 'checkchanges'
      run: |
          if grep -q '^uploadFromGitHub/PoC/pipeline_def_json/' changed_files.txt; then
            echo "Changes detected in pipeline_def_json directory"
            echo "::set-output name=changes::true"
          else
            echo "No changes in pipeline_def_json  directory"
            echo "::set-output name=changes::false"
          fi

    - id: 'auth'
      if: steps.checkchanges.outputs.changes == 'true'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/564758604505/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'pj03-vertex-account@mlpipelineportfolio.iam.gserviceaccount.com'

    - id: 'upload-folder'
      if: steps.checkchanges.outputs.changes == 'true'
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'uploadFromGitHub'
        destination: 'mlpipelineportfolio_bucket_01'
